platform:ios,'8.0'
pod 'RESideMenu'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'SVProgressHUD'
pod 'MJRefresh'
pod 'YYModel'
pod 'SDWebImage'
pod 'BmobSDK'
pod 'UMengSocial','~> 4.3'
pod 'JSAnimatedImagesView'
pod 'FMDB'